version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
    expose:
      - '80'
      - '9000'
    volumes:
      # - ./config.php:/var/www/html/config/config.php
      - app_data:/var/www/html
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=secret
    ports:
      - 8081:80
    expose:
      - '80'
      - '443'
    volumes:
      # - ./sdkjs-plugins:/var/www/onlyoffice/documentserver/sdkjs-plugins/
      - ./plugins/myplugin:/var/www/onlyoffice/documentserver/sdkjs-plugins/myplugin
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
